name: Post commit info to Campfire

on:
  push:
    branches: [ master ]

jobs:
  post-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Post commit info to Campfire
        continue-on-error: true
        uses: shane-lamb/campfire-notify-action@v1.1.6
        with:
          messages_url: ${{ secrets.CAMPFIRE_MESSAGES_URL }}
          template: commit_pushed
