---
name: Docker Container Builds

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:
    inputs:
      dockerPush:
        description: 'Push image to docker hub?'
        required: true
        type: boolean
        default: false
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:24 UTC - build 'nightly' docker containers
    - cron: "24 17 * * *"

  pull_request_target:
    types:
      - labeled

env:
  DOCKER_PUSH: true
jobs:
  pwpush-container:
    if: github.event.label && github.event.label.name == 'docker' || github.event_name != 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/pwpush
          tags: |
            type=ref,event=pr,format=pr-{{ref}}-docker
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush:buildcache
            type=gha
          cache-to: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush:buildcache,mode=max,ignore-error=${{env.DOCKER_PUSH == 'false'}}
            type=gha,mode=max

      - name: Post job failure details to Campfire
        if: failure() && github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: shane-lamb/campfire-notify-action@v1.1.6
        with:
          messages_url: ${{ secrets.CAMPFIRE_MESSAGES_URL }}
          template: job_failed


  public-gateway-container:
    if: github.event.label && github.event.label.name == 'docker' || github.event_name != 'pull_request_target'
    needs: pwpush-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/pwpush-public-gateway
          tags: |
            type=ref,event=pr,format=pr-{{ref}}-docker
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile.public-gateway
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush-public-gateway:buildcache
            type=gha
          cache-to: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush-public-gateway:buildcache,mode=max,ignore-error=${{env.DOCKER_PUSH == 'false'}}
            type=gha,mode=max

      - name: Post job failure details to Campfire
        if: failure() && github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: shane-lamb/campfire-notify-action@v1.1.6
        with:
          messages_url: ${{ secrets.CAMPFIRE_MESSAGES_URL }}
          template: job_failed

  worker-container:
    if: github.event.label && github.event.label.name == 'docker' || github.event_name != 'pull_request_target'
    needs: pwpush-container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'pull_request_target' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/pwpush-worker
          tags: |
            type=ref,event=pr,format=pr-{{ref}}-docker
            type=match,pattern=stable
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/docker/Dockerfile.worker
          platforms: linux/amd64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush-worker:buildcache
            type=gha
          cache-to: |
            type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pwpush-worker:buildcache,mode=max,ignore-error=${{env.DOCKER_PUSH == 'false'}}
            type=gha,mode=max

      - name: Post job failure details to Campfire
        if: failure() && github.ref == 'refs/heads/master'
        continue-on-error: true
        uses: shane-lamb/campfire-notify-action@v1.1.6
        with:
          messages_url: ${{ secrets.CAMPFIRE_MESSAGES_URL }}
          template: job_failed
