---
name: Docker Container Builds

on:
  push:
    tags:
      - "release"
      - "v*.*.*"

  workflow_dispatch:
  #   inputs:
  #     dockerTagName:
  #       description: "What Docker tag to create?"
  #       required: true
  #       default: "development-0xdeadbeef"
  #     dockerPush:
  #       description: "Push image to docker hub?"
  #       required: true
  #       type: boolean
  #       default: false
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every day at 5:24 UTC - build 'latest' docker containers
    - cron: "24 17 * * *"
env:
  DOCKER_PUSH: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dbType: ephemeral
          - dbType: mysql
          - dbType: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Manually configured docker tag
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   run: |
      #     echo "DOCKER_TAG=${{ github.event.inputs.dockerTagName }}" >> $GITHUB_ENV
      #     echo "DOCKER_PUSH=${{ github.event.inputs.dockerPush }}" >> $GITHUB_ENV

      - name: Populate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pglombardo/pwpush-${{ matrix.dbType }}
          flavor: |
            latest=false
          tags: |
            type=match,pattern=release
            type=schedule,pattern=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push pwpush-${{ matrix.dbType }} Docker images
        uses: docker/build-push-action@v4
        with:
          file: ./containers/docker/pwpush-${{ matrix.dbType }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ env.DOCKER_PUSH }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
